name: Demo 05 - Pull Request

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build-test-branch:
    name: "Build and Test Of PR"
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup .NET Core 5.x
    - name: Setup .NET Core 5.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    # Install dependencies
    - name: Install dependencies
      run: dotnet restore "${{ github.workspace }}/mywebapp/mywebapp.sln"

    # Build the project
    - name: Build project
      run: dotnet build "${{ github.workspace }}/mywebapp/mywebapp.sln" --configuration Release --no-restore


    # Publish the project
    - name: Publish project
      run: dotnet publish "${{ github.workspace }}/mywebapp/src/mywebapp.csproj" -c Release -o mywebapp

    # Upload build artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mywebapp-build-artifacts
        path: mywebapp/**
        if-no-files-found: error
        retention-days: 90

    # Run Trivy security scan
    - name: Run security scan with Trivy
      run: |
        trivy fs --scanners vuln,secret,misconfig mywebapp
      continue-on-error: false  # Fail the workflow if vulnerabilities are found

    - uses: snyk/actions/setup@master
      id: snyk
      with:
        snyk-version: v1.391.0
    - uses: actions/setup-go@v1
      with:
        go-version: "1.13"
    - name: Snyk version
      run: echo "${{ steps.snyk.outputs.version }}"
    - name: Snyk monitor 
      run: snyk monitor
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}